server:
  port: ${SERVER_PORT}
spring:
  application:
    name: spacetracker
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_BASE_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml